CREATE TABLE patient (
	id BIGINT NOT NULL,
	name CHAR(50) NULL DEFAULT NULL,
	surname CHAR(50) NULL DEFAULT NULL,
	gender CHAR(50) NULL DEFAULT NULL,
	birthday DATE NULL DEFAULT NULL,
	lifeStatus CHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (id) USING BTREE
);

ALTER TABLE patient ALTER lifeStatus SET DEFAULT 'alive';

CREATE TABLE prophylactic (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name CHAR(50) NULL DEFAULT NULL,
    surname CHAR(50) NULL DEFAULT NULL,
    gender CHAR(20) NULL DEFAULT NULL,
    birthday DATE NULL DEFAULT NULL,
    prophylacticLeave BIGINT(20) NULL DEFAULT NULL,
    PRIMARY KEY (id) USING BTREE
);