CREATE TABLE patient (
	id BIGINT(20) NOT NULL,
	name CHAR(50) NULL DEFAULT NULL,
	surname CHAR(50) NULL DEFAULT NULL,
	gender CHAR(50) NULL DEFAULT NULL,
	birthday DATE NULL DEFAULT NULL,
	sickLeave INT(11) NULL DEFAULT NULL,
	lifeStatus CHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (id) USING BTREE
);

CREATE TABLE prophylactic (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    name CHAR(50) NULL DEFAULT NULL,
    surname CHAR(50) NULL DEFAULT NULL,
    gender CHAR(50) NULL DEFAULT NULL,
    birthday DATE NULL DEFAULT NULL,
    prophylacticLeave INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (id) USING BTREE
);