ALTER TABLE patient
ADD (
zipCode BIGINT NULL DEFAULT NULL,
city CHAR(50) NULL DEFAULT NULL,
street CHAR(50) NULL DEFAULT NULL,
houseNumber INT(10) NULL DEFAULT NULL,
apartmentNumber INT(10) NULL DEFAULT NULL
);