CREATE TABLE sickLeave (
    id BIGINT NOT NULL AUTO_INCREMENT,
    idCard CHAR(50) NULL DEFAULT NULL,
    diagnosis CHAR(100) NULL DEFAULT NULL,
    startOfTreatment DATE NULL DEFAULT NULL,
    endOfTreatment DATE NULL DEFAULT NULL,
    PRIMARY KEY (id) USING BTREE
);